apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-attacher
  namespace: longhorn-system
  labels:
    app: csi-attacher
    longhorn.io/managed-by: longhorn-manager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: csi-attacher
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: csi-attacher
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - csi-attacher
      containers:
      - name: csi-attacher
        image: docker.io/longhornio/csi-attacher:v4.11.0
        imagePullPolicy: IfNotPresent
        args:
        - --v=2
        - --csi-address=$(ADDRESS)
        - --timeout=1m50s
        - --leader-election
        - --leader-election-namespace=$(POD_NAMESPACE)
        - --kube-api-qps=50
        - --kube-api-burst=100
        - --http-endpoint=:8000
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        ports:
        - containerPort: 8000
          name: csi-attacher
          protocol: TCP
        volumeMounts:
        - name: socket-dir
          mountPath: /csi/
      nodeSelector:
        storage.longhorn.io/node: "true"
      priorityClassName: longhorn-critical
      serviceAccountName: longhorn-service-account
      volumes:
      - name: socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/driver.longhorn.io
          type: DirectoryOrCreate
